### ISSUE TITLE
Call expressions not bound correctly

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-stache#232]
__How often can you reproduce it?__ 

- [ ] Always
- [x] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

Call expressions don't work correctly in the latest version of can-stache. For example, the latest code:

```html
<script type="text/stache" id="app">
  <p ($click)="updateObject(obj)">Click Me</p>
  <p>{{obj.value}}</p>

  <my-component />
</script>

<script type="text/stache" id="component">
  <p ($click)="updateCompObj(compObj)">Click Me</p>
  <p>{{compObj.value}}</p>
</script>

<script src="./node_modules/steal/steal.js" main="@loader">
  import DefineMap from 'can-define/map/map';
  import stache from 'can-stache';
  // import Component from 'can-component';

  // Component.extend({
  //   tag: 'my-component',
  //   view: stache.from('component'),
  //   ViewModel: DefineMap.extend({
  //     compObj: {
  //       value: new DefineMap({
  //         value: 0
  //       }),
  //     },
  //     updateCompObj(obj){
  //       console.log('component update', obj);
  //       obj.value ++;
  //     }
  //   })
  // });

  document.body.appendChild(stache.from('app')({
      obj: new DefineMap({
      value: 10
    }),

    updateObject(obj){
      console.log('obj update', obj);
      obj.value ++;
    }
  }));

</script>
```

Works in the previous versions, but in the latest version there are two issues.

1. The event is not actually bound correctly. 
2. If 'can-component' is simply included, the event binding starts to work correctly. 

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-stache version  |  3.2.0
| Browser                    |  Chrome 59
| Operating system    | Windows 7

**Comment by justinbmeyer** [comment]
Without `can-component` (which imports `can-stache-bindings`), event bindings like ` ($click)="updateObject(obj)"` won't work.  I wouldn't consider this a bug.  If this was happening previously, there was likely some dependency cycles that are now fixed.

`can-stache` should not depend on `can-stache-bindings`

**Comment by justinbmeyer** [comment]
Is

> Call expressions convert DefineMap's to plain objects 

not a problem?

**Comment by roemhildtg** [comment]
That's still a problem, but I'm working on reproducing it. I'll make another issue to start discussion.

**Comment by roemhildtg** [comment]
> Without can-component (which imports can-stache-bindings), event bindings like ($click)="updateObject(obj)" won't work. I wouldn't consider this a bug. If this was happening previously, there was likely some dependency cycles that are now fixed.

Okay, I didn't realize can-stache-bindings wasn't automatically imported.

**Comment by justinbmeyer** [comment]
yeah, can-stache-bindings builds ontop of can-stache.  Closing this issue.  I look forward to the next one.
